# Generated by Django 2.1.7 on 2019-03-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190328_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movrotativo',
            name='data_checkin',
            field=models.DateField(),
        ),
    ]
