# Generated by Django 2.1.7 on 2019-03-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190328_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movrotativo',
            name='checkout',
        ),
        migrations.AddField(
            model_name='movrotativo',
            name='data_checkout',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movrotativo',
            name='hora_checkout',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
