# Generated by Django 2.1.7 on 2019-03-28 04:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190328_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movrotativo',
            name='data_checkin',
        ),
        migrations.RemoveField(
            model_name='movrotativo',
            name='data_checkout',
        ),
        migrations.RemoveField(
            model_name='movrotativo',
            name='hora_checkin',
        ),
        migrations.RemoveField(
            model_name='movrotativo',
            name='hora_checkout',
        ),
        migrations.AddField(
            model_name='movrotativo',
            name='checkin',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movrotativo',
            name='checkout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
